tarea_homepage:
    path:     /
    defaults: { _controller: TareaBundle:Default:index }


tarea_create:
    path:     /create
    defaults: { _controller: TareaBundle:Registro:create }


tarea_mostar:
    path:     /mostrar
    defaults: { _controller: TareaBundle:Registro:mostrar }

