tarea_homepage:
    path:     /
    defaults: { _controller: TareaBundle:Default:index }


tarea_create:
    path:     /create
    defaults: { _controller: TareaBundle:Registro:create }


tarea_mostrar:
    path:     /mostrar
    defaults: { _controller: TareaBundle:Registro:mostrar }

tarea_update:
    path:     /update/{id}
    defaults: { _controller: TareaBundle:Registro:update }

tarea_delete:
    path:     /delete/{id}
    defaults: { _controller: TareaBundle:Registro:delete }



